apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-sample-config
data:
  application.yml: |
    spring:
      datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: sa
        password:
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: create-drop
        defer-datasource-initialization: true
      sql:
        init:
          mode: never

    server:
      port: 8080

    management:
      endpoints:
        web:
          exposure:
            include: "*"

    pvc:
      path: /mnt/cloud-sample