apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sampleapp1-82210889-pvc
  namespace: 82210889
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi